//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Laboratório</summary>
	[PublishedContentModel("laboratorio")]
	public partial class Laboratorio : UmbMaster
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "laboratorio";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Laboratorio(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Laboratorio, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("laboratorioHeader")]
		public IPublishedContent LaboratorioHeader
		{
			get { return this.GetPropertyValue<IPublishedContent>("laboratorioHeader"); }
		}

		///<summary>
		/// Texto
		///</summary>
		[ImplementPropertyType("laboratorioTexto")]
		public string LaboratorioTexto
		{
			get { return this.GetPropertyValue<string>("laboratorioTexto"); }
		}

		///<summary>
		/// Título do Texto
		///</summary>
		[ImplementPropertyType("laboratorioTextoTitulo")]
		public string LaboratorioTextoTitulo
		{
			get { return this.GetPropertyValue<string>("laboratorioTextoTitulo"); }
		}

		///<summary>
		/// Chamada
		///</summary>
		[ImplementPropertyType("laboratorioTitulo")]
		public string LaboratorioTitulo
		{
			get { return this.GetPropertyValue<string>("laboratorioTitulo"); }
		}

		///<summary>
		/// Título das Imagens
		///</summary>
		[ImplementPropertyType("laboratorioTituloDasImagens")]
		public string LaboratorioTituloDasImagens
		{
			get { return this.GetPropertyValue<string>("laboratorioTituloDasImagens"); }
		}
	}
}
