//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Laboratório Item</summary>
	[PublishedContentModel("laboratorioItem")]
	public partial class LaboratorioItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "laboratorioItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LaboratorioItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LaboratorioItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Imagem
		///</summary>
		[ImplementPropertyType("laboratorioItemImagem")]
		public IPublishedContent LaboratorioItemImagem
		{
			get { return this.GetPropertyValue<IPublishedContent>("laboratorioItemImagem"); }
		}

		///<summary>
		/// Legenda
		///</summary>
		[ImplementPropertyType("laboratorioItemLegenda")]
		public string LaboratorioItemLegenda
		{
			get { return this.GetPropertyValue<string>("laboratorioItemLegenda"); }
		}
	}
}
