//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Pistas Item</summary>
	[PublishedContentModel("pistasItem")]
	public partial class PistasItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pistasItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PistasItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PistasItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("pistaItemHeader")]
		public IPublishedContent PistaItemHeader
		{
			get { return this.GetPropertyValue<IPublishedContent>("pistaItemHeader"); }
		}

		///<summary>
		/// Imagem da Pista
		///</summary>
		[ImplementPropertyType("pistaItemImage")]
		public IPublishedContent PistaItemImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("pistaItemImage"); }
		}

		///<summary>
		/// Imagens
		///</summary>
		[ImplementPropertyType("pistaItemImagens")]
		public IEnumerable<IPublishedContent> PistaItemImagens
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("pistaItemImagens"); }
		}

		///<summary>
		/// Número
		///</summary>
		[ImplementPropertyType("pistaItemNumero")]
		public string PistaItemNumero
		{
			get { return this.GetPropertyValue<string>("pistaItemNumero"); }
		}

		///<summary>
		/// Texto
		///</summary>
		[ImplementPropertyType("pistaItemTexto")]
		public IHtmlString PistaItemTexto
		{
			get { return this.GetPropertyValue<IHtmlString>("pistaItemTexto"); }
		}

		///<summary>
		/// Título
		///</summary>
		[ImplementPropertyType("pistaItemTitulo")]
		public string PistaItemTitulo
		{
			get { return this.GetPropertyValue<string>("pistaItemTitulo"); }
		}

		///<summary>
		/// Vídeo
		///</summary>
		[ImplementPropertyType("pistaItemVideo")]
		public Newtonsoft.Json.Linq.JToken PistaItemVideo
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("pistaItemVideo"); }
		}
	}
}
