//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("umbHomePage")]
	public partial class UmbHomePage : UmbMaster
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbHomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbHomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbHomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Coordenadas S
		///</summary>
		[ImplementPropertyType("coordinatesS")]
		public string CoordinatesS
		{
			get { return this.GetPropertyValue<string>("coordinatesS"); }
		}

		///<summary>
		/// Coordenadas W
		///</summary>
		[ImplementPropertyType("coordinatesW")]
		public string CoordinatesW
		{
			get { return this.GetPropertyValue<string>("coordinatesW"); }
		}

		///<summary>
		/// E-mail
		///</summary>
		[ImplementPropertyType("eMail")]
		public string EMail
		{
			get { return this.GetPropertyValue<string>("eMail"); }
		}

		///<summary>
		/// Endereço - Linha 1
		///</summary>
		[ImplementPropertyType("enderecoLinha1")]
		public string EnderecoLinha1
		{
			get { return this.GetPropertyValue<string>("enderecoLinha1"); }
		}

		///<summary>
		/// Endereço - Linha 2
		///</summary>
		[ImplementPropertyType("enderecoLinha2")]
		public string EnderecoLinha2
		{
			get { return this.GetPropertyValue<string>("enderecoLinha2"); }
		}

		///<summary>
		/// Hectares
		///</summary>
		[ImplementPropertyType("hectares")]
		public string Hectares
		{
			get { return this.GetPropertyValue<string>("hectares"); }
		}

		///<summary>
		/// Imagem
		///</summary>
		[ImplementPropertyType("homeBanner1Image")]
		public IPublishedContent HomeBanner1Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("homeBanner1Image"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("homeBanner1Link")]
		public string HomeBanner1Link
		{
			get { return this.GetPropertyValue<string>("homeBanner1Link"); }
		}

		///<summary>
		/// Sub-título
		///</summary>
		[ImplementPropertyType("homeBanner1SubTitulo")]
		public string HomeBanner1SubTitulo
		{
			get { return this.GetPropertyValue<string>("homeBanner1SubTitulo"); }
		}

		///<summary>
		/// Texto do link
		///</summary>
		[ImplementPropertyType("homeBanner1TextoDoLink")]
		public string HomeBanner1TextoDoLink
		{
			get { return this.GetPropertyValue<string>("homeBanner1TextoDoLink"); }
		}

		///<summary>
		/// Título
		///</summary>
		[ImplementPropertyType("homeBanner1Titulo")]
		public string HomeBanner1Titulo
		{
			get { return this.GetPropertyValue<string>("homeBanner1Titulo"); }
		}

		///<summary>
		/// Imagem
		///</summary>
		[ImplementPropertyType("homeBanner2Imagem")]
		public IPublishedContent HomeBanner2Imagem
		{
			get { return this.GetPropertyValue<IPublishedContent>("homeBanner2Imagem"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("homeBanner2Link")]
		public string HomeBanner2Link
		{
			get { return this.GetPropertyValue<string>("homeBanner2Link"); }
		}

		///<summary>
		/// Sub-título
		///</summary>
		[ImplementPropertyType("homeBanner2SubTitulo")]
		public string HomeBanner2SubTitulo
		{
			get { return this.GetPropertyValue<string>("homeBanner2SubTitulo"); }
		}

		///<summary>
		/// Texto do Link
		///</summary>
		[ImplementPropertyType("homeBanner2TextoDoLink")]
		public string HomeBanner2TextoDoLink
		{
			get { return this.GetPropertyValue<string>("homeBanner2TextoDoLink"); }
		}

		///<summary>
		/// Título
		///</summary>
		[ImplementPropertyType("homeBanner2Titulo")]
		public string HomeBanner2Titulo
		{
			get { return this.GetPropertyValue<string>("homeBanner2Titulo"); }
		}

		///<summary>
		/// Box 1 - Texto
		///</summary>
		[ImplementPropertyType("homeBox1Titulo")]
		public IHtmlString HomeBox1Titulo
		{
			get { return this.GetPropertyValue<IHtmlString>("homeBox1Titulo"); }
		}

		///<summary>
		/// Box 2 - Link
		///</summary>
		[ImplementPropertyType("homeBox2Link")]
		public string HomeBox2Link
		{
			get { return this.GetPropertyValue<string>("homeBox2Link"); }
		}

		///<summary>
		/// Box 2 - Texto
		///</summary>
		[ImplementPropertyType("homeBox2Texto")]
		public string HomeBox2Texto
		{
			get { return this.GetPropertyValue<string>("homeBox2Texto"); }
		}

		///<summary>
		/// Box 2 - Título
		///</summary>
		[ImplementPropertyType("homeBox2Titulo")]
		public string HomeBox2Titulo
		{
			get { return this.GetPropertyValue<string>("homeBox2Titulo"); }
		}

		///<summary>
		/// Box 3 - Link
		///</summary>
		[ImplementPropertyType("homeBox3Link")]
		public string HomeBox3Link
		{
			get { return this.GetPropertyValue<string>("homeBox3Link"); }
		}

		///<summary>
		/// Box 3 - Texto
		///</summary>
		[ImplementPropertyType("homeBox3Texto")]
		public string HomeBox3Texto
		{
			get { return this.GetPropertyValue<string>("homeBox3Texto"); }
		}

		///<summary>
		/// Box 3 - Título
		///</summary>
		[ImplementPropertyType("homeBox3Titulo")]
		public string HomeBox3Titulo
		{
			get { return this.GetPropertyValue<string>("homeBox3Titulo"); }
		}

		///<summary>
		/// Box 4 - Imagem
		///</summary>
		[ImplementPropertyType("homeBox4Imagem")]
		public IPublishedContent HomeBox4Imagem
		{
			get { return this.GetPropertyValue<IPublishedContent>("homeBox4Imagem"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("homePistasLink")]
		public string HomePistasLink
		{
			get { return this.GetPropertyValue<string>("homePistasLink"); }
		}

		///<summary>
		/// Texto do Link
		///</summary>
		[ImplementPropertyType("homePistasTextoDoLink")]
		public string HomePistasTextoDoLink
		{
			get { return this.GetPropertyValue<string>("homePistasTextoDoLink"); }
		}

		///<summary>
		/// Vídeo
		///</summary>
		[ImplementPropertyType("homeVideo")]
		public Newtonsoft.Json.Linq.JToken HomeVideo
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("homeVideo"); }
		}

		///<summary>
		/// Imagem
		///</summary>
		[ImplementPropertyType("imagem")]
		public IPublishedContent Imagem
		{
			get { return this.GetPropertyValue<IPublishedContent>("imagem"); }
		}

		///<summary>
		/// Latitude
		///</summary>
		[ImplementPropertyType("latitude")]
		public string Latitude
		{
			get { return this.GetPropertyValue<string>("latitude"); }
		}

		///<summary>
		/// Link Google Maps
		///</summary>
		[ImplementPropertyType("linkGoogleMaps")]
		public string LinkGoogleMaps
		{
			get { return this.GetPropertyValue<string>("linkGoogleMaps"); }
		}

		///<summary>
		/// Longitude
		///</summary>
		[ImplementPropertyType("longitude")]
		public string Longitude
		{
			get { return this.GetPropertyValue<string>("longitude"); }
		}

		///<summary>
		/// Metros Quadrados
		///</summary>
		[ImplementPropertyType("metrosQuadrados")]
		public string MetrosQuadrados
		{
			get { return this.GetPropertyValue<string>("metrosQuadrados"); }
		}

		///<summary>
		/// Metros Quadrados - Sub-título
		///</summary>
		[ImplementPropertyType("metrosQuadradosSubTitulo")]
		public string MetrosQuadradosSubTitulo
		{
			get { return this.GetPropertyValue<string>("metrosQuadradosSubTitulo"); }
		}

		///<summary>
		/// Quilômetros
		///</summary>
		[ImplementPropertyType("quilometros")]
		public string Quilometros
		{
			get { return this.GetPropertyValue<string>("quilometros"); }
		}

		///<summary>
		/// Título do Site
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		///<summary>
		/// Telefone
		///</summary>
		[ImplementPropertyType("telefone")]
		public string Telefone
		{
			get { return this.GetPropertyValue<string>("telefone"); }
		}

		///<summary>
		/// Texto
		///</summary>
		[ImplementPropertyType("textoIntrodutorio")]
		public string TextoIntrodutorio
		{
			get { return this.GetPropertyValue<string>("textoIntrodutorio"); }
		}

		///<summary>
		/// Tipos de Pista
		///</summary>
		[ImplementPropertyType("tiposDePista")]
		public string TiposDePista
		{
			get { return this.GetPropertyValue<string>("tiposDePista"); }
		}
	}
}
